export const EMAIL_IS_NOT_VALID = 'Email is Not Valid'
export const USER_ALREADY_EXISTS = 'User Already Exists'
export const USER_DOES_NOT_EXIST = 'User does not Exist'
export const INVALID_PASSWORD = 'Invalid Password'
export const INTERNAL_SERVER_ERROR = 'Internal Server Error'